name: DoIT-Maven-Deploy

on:
  push:
    branches: [main]

env:
  S3_BUCKET_NAME: doit-build-file
  PROJECT_NAME: doit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application.properties
        run: |
          mkdir -p ./src/main/resources
          cat <<EOF > ./src/main/resources/application.properties
          spring.application.name=backend
          spring.datasource.url=${{ secrets.DB_URL }}
          spring.datasource.username=${{ secrets.DB_USERNAME }}
          spring.datasource.password=${{ secrets.DB_PASSWORD }}
          spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
          spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
          server.port=8090
          server.servlet.session.cookie.secure=true
          server.servlet.session.cookie.http-only=true
          mybatis.mapper-locations=classpath:mappers/*.xml
          mybatis.configuration.map-underscore-to-camel-case=true
          mybatis.type-aliases-package=com.Fm.backend.model
          kakao.api-key=${{ secrets.KAKAO_API_KEY }}
          kakao.admin-key=${{ secrets.KAKAO_ADMIN_KEY }}
          kakao.redirect_uri=${{ secrets.KAKAO_REDIRECT_URI }}
          kakao.access-token-url=https://kauth.kakao.com/oauth/token
          kakao.user-info-url=https://kapi.kakao.com/v2/user/me
          spring.servlet.multipart.max-file-size=10MB
          spring.servlet.multipart.max-request-size=10MB
          EOF

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Make ZIP file
        run: zip -r ${{ github.sha }}.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp ${{ github.sha }}.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/${{ github.sha }}.zip
